abstract class DisplayableEnum {
  String get displayName;
}

enum SortType implements DisplayableEnum {
  metaScore("Algorithm"),
  popularity("Most Popular"),
  healthiness("Most Healthy"),
  price("Lowest Price"),
  time("Quickist Cook Time"),
  random("random");

  @override
  final String displayName;
  const SortType(this.displayName);
}

enum MealType implements DisplayableEnum {
  mainCourse("main course"),
  sideDish("side dish"),
  dessert("dessert"),
  appetizer("appetizer"),
  salad("salad"),
  bread("bread"),
  breakfast("breakfast"),
  soup("soup"),
  beverage("beverage"),
  sauce("sauce"),
  marinade("marinade"),
  fingerfood("fingerfood"),
  snack("snack"),
  drink("drink"),
  lunch("lunch");

  @override
  final String displayName;
  const MealType(this.displayName);
}

enum CuisineType implements DisplayableEnum {
  african("African"),
  asian("Asian"),
  american("American"),
  british("British"),
  cajun("Cajun"),
  caribbean("Caribbean"),
  chinese("Chinese"),
  easternEuropean("Eastern European"),
  european("European"),
  french("French"),
  german("German"),
  greek("Greek"),
  indian("Indian"),
  irish("Irish"),
  italian("Italian"),
  japanese("Japanese"),
  jewish("Jewish"),
  korean("Korean"),
  latinAmerican("Latin American"),
  mediterranean("Mediterranean"),
  mexican("Mexican"),
  middleEastern("Middle Eastern"),
  nordic("Nordic"),
  southern("Southern"),
  spanish("Spanish"),
  thai("Thai"),
  vietnamese("Vietnamese");

  @override
  final String displayName;
  const CuisineType(this.displayName);
}

enum DietType implements DisplayableEnum {
  glutenFree("Gluten Free"),
  ketogenic("Ketogenic"),
  vegetarian("Vegetarian"),
  lactoVegetarian("Lacto-Vegetarian"),
  ovoVegetarian("Ovo-Vegetarian"),
  vegan("Vegan"),
  pescetarian("Pescetarian"),
  paleo("Paleo"),
  primal("Primal"),
  lowFodmap("Low FODMAP"),
  whole30("Whole30");

  @override
  final String displayName;
  const DietType(this.displayName);
}

enum IntoleranceType implements DisplayableEnum {
  dairy("Dairy"),
  egg("Egg"),
  gluten("Gluten"),
  grain("Grain"),
  peanut("Peanut"),
  seafood("Seafood"),
  sesame("Sesame"),
  shellfish("Shellfish"),
  soy("Soy"),
  sulfite("Sulfite"),
  treeNut("Tree Nut"),
  wheat("Wheat");

  @override
  final String displayName;
  const IntoleranceType(this.displayName);
}

enum EquipmentType implements DisplayableEnum {
  skimmer("skimmer"),
  pieForm("pie form"),
  glassBakingPan("glass baking pan"),
  garlicPress("garlic press"),
  meatGrinder("meat grinder"),
  tongs("tongs"),
  breadKnife("bread knife"),
  tajinePot("tajine pot"),
  wireRack("wire rack"),
  mincingKnife("mincing knife"),
  cherryPitter("cherry pitter"),
  woodenSkewers("wooden skewers"),
  kitchenScissors("kitchen scissors"),
  blowTorch("blow torch"),
  broilerPan("broiler pan"),
  heartShapedSiliconeForm("heart shaped silicone form"),
  grill("grill"),
  immersionBlender("immersion blender"),
  bakingSheet("baking sheet"),
  ovenMitt("oven mitt"),
  pastryBag("pastry bag"),
  paletteKnife("palette knife"),
  pizzaCutter("pizza cutter"),
  bottleOpener("bottle opener"),
  bowl("bowl"),
  pizzaPan("pizza pan"),
  candyThermometer("candy thermometer"),
  rollingPin("rolling pin"),
  fryingPan("frying pan"),
  casseroleDish("casserole dish"),
  plasticWrap("plastic wrap"),
  saladSpinner("salad spinner"),
  broiler("broiler"),
  siliconeMuffinTray("silicone muffin tray"),
  meatTenderizer("meat tenderizer"),
  edibleCakeImage("edible cake image"),
  measuringSpoon("measuring spoon"),
  kitchenThermometer("kitchen thermometer"),
  sifter("sifter"),
  muffinTray("muffin tray"),
  chocolateMold("chocolate mold"),
  kitchenTowels("kitchen towels"),
  potatoRicer("potato ricer"),
  siliconeKugelhopfPan("silicone kugelhopf pan"),
  offsetSpatula("offset spatula"),
  cheesecloth("cheesecloth"),
  lemonSqueezer("lemon squeezer"),
  cakeForm("cake form"),
  miniMuffinTray("mini muffin tray"),
  carvingFork("carving fork"),
  eggSlicer("egg slicer"),
  iceCubeTray("ice cube tray"),
  corkscrew("corkscrew"),
  iceCreamMachine("ice cream machine"),
  sieve("sieve"),
  kugelhopfPan("kugelhopf pan"),
  pastryBrush("pastry brush"),
  popsicleSticks("popsicle sticks"),
  spatula("spatula"),
  cakeServer("cake server"),
  poultryShears("poultry shears"),
  boxGrater("box grater"),
  cupcakeToppers("cupcake toppers"),
  funnel("funnel"),
  drinkingStraws("drinking straws"),
  slottedSpoon("slotted spoon"),
  ceramicPieForm("ceramic pie form"),
  pepperGrinder("pepper grinder"),
  mortarAndPestle("mortar and pestle"),
  baster("baster"),
  melonBaller("melon baller"),
  zester("zester"),
  pastryCutter("pastry cutter"),
  ziplocBags("ziploc bags"),
  aluminumFoil("aluminum foil"),
  toothpicks("toothpicks"),
  pot("pot"),
  bakingPan("baking pan"),
  ladle("ladle"),
  appleCutter("apple cutter"),
  filletKnife("fillet knife"),
  toaster("toaster"),
  heartShapedCakeForm("heart shaped cake form"),
  grillPan("grill pan"),
  woodenSpoon("wooden spoon"),
  paperTowels("paper towels"),
  cookieCutter("cookie cutter"),
  tartForm("tart form"),
  pizzaBoard("pizza board"),
  glassCasseroleDish("glass casserole dish"),
  madeleineForm("madeleine form"),
  metalSkewers("metal skewers"),
  microplane("microplane"),
  standMixer("stand mixer"),
  whisk("whisk"),
  mixingBowl("mixing bowl"),
  deepFryer("deep fryer"),
  canningJar("canning jar"),
  cheeseKnife("cheese knife"),
  handMixer("hand mixer"),
  butterCurler("butter curler"),
  foodProcessor("food processor"),
  waxPaper("wax paper"),
  grater("grater"),
  gravyBoat("gravy boat"),
  muffinLiners("muffin liners"),
  butterKnife("butter knife"),
  waffleIron("waffle iron"),
  doubleBoiler("double boiler"),
  canOpener("can opener"),
  mandoline("mandoline"),
  kitchenTwine("kitchen twine"),
  juicer("juicer"),
  wok("wok"),
  measuringCup("measuring cup"),
  ramekin("ramekin"),
  airfryer("airfryer"),
  instantPot("instant pot"),
  spoon("spoon"),
  doughScraper("dough scraper"),
  microwave("microwave"),
  roastingPan("roasting pan"),
  pressureCooker("pressure cooker"),
  dehydrator("dehydrator"),
  bakingPaper("baking paper"),
  siliconeMuffinLiners("silicone muffin liners"),
  loafPan("loaf pan"),
  cakeTopper("cake topper"),
  dutchOven("dutch oven"),
  bakingSpatula("baking spatula"),
  popsicleMolds("popsicle molds"),
  teapot("teapot"),
  cocktailSticks("cocktail sticks"),
  cleaver("cleaver"),
  riceCooker("rice cooker"),
  breadMachine("bread machine"),
  fork("fork"),
  iceCreamScoop("ice cream scoop"),
  slowCooker("slow cooker"),
  knife("knife"),
  kitchenScale("kitchen scale"),
  griddle("griddle"),
  frostingCakeTopper("frosting cake topper"),
  cuttingBoard("cutting board"),
  cakePopMold("cake pop mold"),
  oven("oven"),
  colander("colander"),
  kitchenTimer("kitchen timer"),
  paniniPress("panini press"),
  pastaMachine("pasta machine"),
  popcornMaker("popcorn maker"),
  lollipopSticks("lollipop sticks"),
  steamerBasket("steamer basket"),
  chopsticks("chopsticks"),
  chefsKnife("chefs knife"),
  blender("blender"),
  pizzaStone("pizza stone"),
  skewers("skewers"),
  saucePan("sauce pan"),
  peeler("peeler"),
  stove("stove"),
  potHolder("pot holder"),
  springformPan("springform pan"),
  appleCorer("apple corer"),
  potatoMasher("potato masher"),
  serratedKnife("serrated knife");

  @override
  final String displayName;
  const EquipmentType(this.displayName);
}
